version: '2'
services:
    ra_bbvet-app:
        image: ra_bbvet
        external_links:
            - ra_bbvet-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ra_bbvet?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ra_bbvet-mysql:
        extends:
            file: mysql.yml
            service: ra_bbvet-mysql
